### PR TITLE
make the Example work with current configuration

### PR DESCRIPTION
**Pull request by schurzi**
I had some pretty hard problems getting your example to run on my system. After a lot of digging around I think I found the minimal set of changes to make this run with the provided documentation.

If you are interested I may also be able to add some documentation to run this with docker.

### CODE REVIEW

**Comment by JanThiel** [comment]
Thank you very much for your feedback and contribution @schurzi

We might have forgotten to update the example project for some time... obviously :-/ Sorry for the hassle!

If you can provide some docs about how to run the 3PPP in Docker we are happy to have them :-)

Hope you like it anyway :-)

**Comment by schurzi** [comment]
You're welcome! I had some worries that this project might be abandoned. This fast reaction caught me by surprise ^^

We are currently evaluating your software for our project. I think if things come out positive I will ad some more contributions.

As for this PR, I would like to keep it small and focused so I want to add the Docker stuff in a separate PR.

**Comment by JanThiel** [comment]
> I had some worries that this project might be abandoned. This fast reaction caught me by surprise ^^

Abandoned is such a harsh word ;-) Let's call it "Feature Complete" for what we needed. The core library ( https://github.com/DieTechniker/3rdparty-privacy-proxy ) is still a core component of our website and as such will continue to get relevant updates. As this is "just" the example implementation, it might not get the attention it ~~requires~~ deserves. Just for context.

That said, please keep in mind that the core library is https://github.com/DieTechniker/3rdparty-privacy-proxy and that relevant global feature should be added there.

I will see that we get your changes checked and merged. Please allow some days of time due to the short weeks and vacation time.

**Review by kassimhoelting — DISMISSED** [review]
Sorry for the late response. I saw the PR on my vacation + corona time and forgot about it^^

**Pull request merged**
